openapi: "3.0.0"
info:
  title: DM OpenAPI 文档
  version: "2.0.6"
externalDocs:
  description: "DM 相关文档"
  url: "https://docs.pingcap.com/zh/tidb-data-migration/stable"
servers:
  - url: "https://you.domain.com/"
tags:
  - name: source
    description: 数据源相关
    externalDocs:
      description: doc
      url: "https://docs.pingcap.com/zh/tidb-data-migration/stable/quick-start-create-source"
  - name: task
    description: 迁移任务相关
    externalDocs:
      description: doc
      url: "https://docs.pingcap.com/zh/tidb-data-migration/stable/quick-create-migration-task"

paths:
  /api/v1/sources:
    post:
      tags:
        - source
      summary: "创建新的数据源"
      operationId: "DMAPICreateSource"
      requestBody:
        description: "请求体"
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Source"
      responses:
        "201":
          description: "创建成功"
        "400":
          description: "创建失败"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ErrorWithMessage"
    get:
      tags:
        - source
      summary: "获取所有数据源列表"
      operationId: "DMAPIGetSourceList"
      responses:
        "200":
          description: "数据源列表"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Source"
  /api/v1/sources/{source-name}:
    delete:
      tags:
        - source
      summary: "删除数据源"
      operationId: "DMAPIDeleteSource"
      parameters:
        - name: "source-name"
          in: path
          description: "全局唯一的数据源名字"
          required: true
          schema:
            type: string
            example: "mysql-01"
      responses:
        "204":
          description: "删除成功"
        "400":
          description: "删除失败"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ErrorWithMessage"
  /api/v1/sources/{source-name}/status:
    get:
      tags:
        - source
      summary: "查询数据源的当前状态"
      operationId: "DMAPIGetSourceStatus"
      parameters:
        - name: source-name
          in: path
          description: "全局唯一的数据源名"
          required: true
          schema:
            type: string
            example: "mysql-replica-01"
      responses:
        "200":
          description: "获取成功"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/SourceStatus"
        "400":
          description: "获取失败"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ErrorWithMessage"
  /api/v1/sources/{source-name}/start-relay:
    patch:
      tags:
        - source
      summary: "为数据源开启 relay log 功能"
      operationId: "DMAPIStartRelay"
      parameters:
        - name: "source-name"
          in: path
          description: "全局唯一的数据源名字"
          required: true
          schema:
            type: string
            example: "mysql-01"
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/StartRelayRequest"
      responses:
        "200":
          description: "开启成功"
        "400":
          description: "开启失败"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ErrorWithMessage"
  /api/v1/sources/{source-name}/stop-relay:
    patch:
      tags:
        - source
      summary: "为数据源关闭 relay log 功能"
      operationId: "DMAPIStopRelay"
      parameters:
        - name: "source-name"
          in: path
          description: "全局唯一的数据源名字"
          required: true
          schema:
            type: string
            example: "mysql-01"
      requestBody:
        required: true
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/WorkerNameRequest"
      responses:
        "200":
          description: "开启成功"
        "400":
          description: "开启失败"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ErrorWithMessage"

  /api/v1/tasks:
    post:
      tags:
        - task
      summary: "提交并开始任务"
      operationId: "DMAPIStartTask"
      requestBody:
        description: "请求体"
        content:
          "application/json":
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: "创建任务成功成功"
        "400":
          description: "创建失败"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ErrorWithMessage"
    get:
      tags:
        - task
      summary: "获取当前所有任务的信息"
      operationId: "DMAPIGetTaskList"
      responses:
        "200":
          description: "当前 task 的列表"
          content:
            "application/json":
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
        "400":
          description: "创建失败"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ErrorWithMessage"
  /api/v1/tasks/{task-name}:
    delete:
      tags:
        - task
      summary: "删除任务"
      operationId: "DMAPIDeleteTask"
      parameters:
        - name: task-name
          in: path
          description: "全局唯一的任务名"
          required: true
          schema:
            type: string
            example: "task-1"
      responses:
        "204":
          description: "删除成功"
        "400":
          description: "删除失败"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ErrorWithMessage"
  /api/v1/tasks/{task-name}/status:
    get:
      tags:
        - task
      summary: "查询任务当前状态"
      operationId: "DMAPIGetTaskStatus"
      parameters:
        - name: task-name
          in: path
          description: "全局唯一的任务名"
          required: true
          schema:
            type: string
            example: "task-1"
      responses:
        "200":
          description: "获取成功"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/SubTaskStatus"
        "400":
          description: "获取失败"
          content:
            "application/json":
              schema:
                $ref: "#/components/schemas/ErrorWithMessage"

components:
  schemas:
    Security:
      type: object
      description: "数据源 ssl 配置,从接口获取数据源配置时，该字段会被隐藏"
      nullable: true
      properties:
        ssl_ca_content:
          type: string
          example: ""
          description: "根证书文件内容"
          nullable: true
        ssl_cert_content:
          type: string
          example: ""
          description: "PEM格式/X509格式证书的文件内容"
          nullable: true
        ssl_key_content:
          type: string
          example: ""
          description: "X509格式的私钥文件内容"
          nullable: true
    Purge:
      description: "relay log 清理策略配置"
      type: object
      properties:
        interval:
          type: integer
          default: 3600
          description: "定期检查 relay log 是否过期的间隔时间，默认值：3600，单位：秒"
          nullable: true
        expires:
          type: integer
          default: 0
          description: "relay log 的过期时间，默认值为 0，单位：小时。未由 relay 处理单元进行写入、或已有数据迁移任务当前或未来不需要读取的 relay log 在超过过期时间后会被 DM 删除。如果不设置则 DM 不会自动清理过期的 relay log。"
          nullable: true
        remain_space:
          type: integer
          default: 15
          description: "设置最小的可用磁盘空间。当磁盘可用空间小于这个值时，DM-worker 会尝试删除 relay log，默认值：15，单位：GB"
          nullable: true
    RelayStatus:
      description: "relay log 的状态"
      type: object
      properties:
        master_binlog:
          type: string
          example: "(mysql-bin.000001, 1979)"
          description: "上游 binlog file的信息"
        master_binlog_gtid:
          type: string
          example: "e9a1fc22-ec08-11e9-b2ac-0242ac110003:1-7849"
          description: "上游 binlog 的 GTID"
        relay_sub_dir:
          type: string
          description: "存储 relay log 的目录"
          example: "b8ba86a4-a3d5-11eb-95ce-1add06868d30.000001"
        relay_binlog_gtid:
          type: string
          example: "e9a1fc22-ec08-11e9-b2ac-0242ac110003:1-7849"
          description: "relay 当前的 GTID"
        relay_catch_up_master:
          type: boolean
          description: "relay log 是否追上上游的进度"
        stage:
          type: string
          description: "当前状态"
          example: "Running"
    StartRelayRequest:
      description: 操作是否开启 relay 的请求
      type: object
      properties:
        worker_name:
          type: string
          example: "worker-1"
          description: "woker 的名字，需要全局唯一"
        relay_binlog_name:
          type: string
          example: "mysql-bin.000002"
          description: "拉取上游 binlog 的起始文件名"
          nullable: true
        relay_binlog_gtid:
          type: string
          example: "e9a1fc22-ec08-11e9-b2ac-0242ac110003:1-7849"
          description: "拉取上游 binlog 的起始 GTID"
          nullable: true
        relay_dir:
          type: string
          default: "./relay_log"
          description: "存储 relay log 的目录"
          nullable: true
        pruge:
          $ref: "#/components/schemas/Purge"
    WorkerNameRequest:
      description: 和 worker 相关的请求
      type: object
      properties:
        worker_name:
          type: string
          example: "worker-1"
          description: "woker 的名字，需要全局唯一"
    SourceStatus:
      description: "数据源的状态"
      type: object
      properties:
        source_name:
          type: string
          example: "mysql-replica-01"
          description: "数据源 ID"
        worker_name:
          type: string
          example: "worker-1"
          description: "当前 source 绑定的 worker"
        enable_relay:
          type: boolean
          example: false
          default: false
          description: "是否开启 relay log，默认值为 false"
        relay_status:
          $ref: "#/components/schemas/RelayStatus"
    Source:
      type: object
      description: "数据源"
      properties:
        source_name:
          type: string
          example: "mysql-01"
          description: "数据源名字，需要全局唯一"
        host:
          type: string
          example: "127.0.0.1"
          description: "数据源地址"
        port:
          type: integer
          example: 3306
          description: "数据源端口"
        user:
          type: string
          example: "root"
          description: "数据库用户名"
        password:
          type: string
          example: "123456"
          description: "数据库密码"
        enable_gtid:
          type: boolean
          example: false
          default: false
          description: "是否使用 GTID 方式从上游拉取 binlog"
        security:
          $ref: "#/components/schemas/Security"
    TaskTargetDataBase:
      type: object
      description: "下游数据库配置"
      properties:
        host:
          type: string
          example: "127.0.0.1"
          description: "数据源地址"
        port:
          type: integer
          example: 3306
          description: "数据源端口"
        user:
          type: string
          example: "root"
          description: "数据库用户名"
        password:
          type: string
          example: "123456"
          description: "数据库密码"
        security:
          $ref: "#/components/schemas/Security"

    TaskEventFilterRule:
      description: "binlog 级别的过滤规则"
      type: object
      properties:
        rule_name:
          type: string
          example: "rule-1"
          description: "过滤规则名"
        ignore_event:
          description: "过滤哪些 event 类型"
          type: array
          items:
            type: string
            description: "事件类型"
            example: "all dml"
        ignore_sql:
          description: "过滤哪些sql类型"
          type: array
          items:
            type: string
            description: "事件类型"
            example: "^Drop"
    TaskTableMigrateRule:
      type: object
      description: "上游表到下游的同步规则"
      properties:
        source:
          type: object
          description: 数据源相关配置
          properties:
            source_name:
              type: string
              description: 数据源名字,支持通配符
              example: "source-*"
            schema:
              type: string
              description: 数据库名字,支持通配符
              example: "db-*"
            table:
              type: string
              description: 表名字,支持通配符
              example: "tb-*"
        target:
          type: object
          description: 下游相关配置
          properties:
            schema:
              type: string
              description: 数据库名字,不支持通配符
              example: "db1"
            table:
              type: string
              description: 表名字,不支持通配符
              example: "tb1"
        event_filter:
          type: array
          description: "过滤规则名字"
          items:
            type: string
            example: rule-1
    TaskSourceConfig:
      type: object
      description: "任务针对数据源的配置"
      properties:
        full_migrate_conf:
          description: 全量任务的配置
          type: object
          properties:
            export_threads:
              type: integer
              description: 全量导出并发配置。默认 4
              default: 4
            import_threads:
              type: integer
              description: 全量导入并发配置。默认 4
              default: 16
            data_dir:
              type: string
              example: "./exported_data"
              description: "存储目录，保留可以承载全量数据的足够空间"
            consistency:
              type: string
              example: ""
              description: "一致性保证"
              enum:
                - "snapshot"
                - "none"
        incr_migrate_conf:
          description: 全量任务的配置
          type: object
          properties:
            repl_threads:
              type: integer
              description: 增量同步的并发配置
              default: 32
            batch:
              type: integer
              description: 增量同步的攒批配置
              default: 200
        source:
          type: array
          description: 每个数据源的配置
          items:
            type: object
            properties:
              source_name:
                type: string
                example: "mysql-replica-01"
                description: "数据源名"
              binlog_name:
                type: string
                example: "binlog.000001"
              binlog_pos:
                type: integer
                example: 4
              binlog_gtid:
                type: string
                description: "对于 source 中指定了 enable-gtid: true 的增量任务，需要指定该值"
                example: "03fc0263-28c7-11e7-a653-6c0b84d59f30:1-7041423,05474d3c-28c7-11e7-8352-203db246dd3d:1-170"

    ShardingGroup:
      type: object
      properties:
        target:
          type: string
        ddl_list:
          type: array
          items:
            type: string
          description: ""
        first_location:
          type: string
        synced:
          type: array
          items:
            type: string
          description: ""
        unsynced:
          type: array
          items:
            type: string
          description: ""
    LoadStatus:
      type: object
      description: "load 单元子任务的状态"
      properties:
        finished_bytes:
          type: integer
          format: int64
        total_bytes:
          type: integer
          format: int64
        progress:
          type: string
        meta_binlog:
          type: string
        meta_binlog_gtid:
          type: string
    SyncStatus:
      type: object
      description: "load 单元子任务的状态"
      properties:
        total_events:
          type: integer
          format: int64
        total_tps:
          type: integer
          format: int64
        recent_tps:
          type: integer
          format: int64
        master_binlog:
          type: string
        master_binlog_gtid:
          type: string
        syncer_binlog:
          type: string
        syncer_binlog_gtid:
          type: string
        blocking_ddls:
          type: array
          items:
            type: string
          description: sharding DDL which current is blocking
        unresolved_groups:
          type: array
          items:
            $ref: "#/components/schemas/ShardingGroup"
          description: sharding groups which current are un-resolved
        synced:
          type: boolean
        binlog_type:
          type: string
        seconds_behind_master:
          type: integer
    SubTaskStatus:
      type: object
      properties:
        name:
          type: string
          description: "任务名字"
        stage:
          type: string
          example: "runing"
          description: "任务当前阶段"
        unit:
          type: string
          example: "sync"
          description: "任务单元类型"
        unresolved_ddl_lock_id:
          type: string
        load_status:
          nullable: true
          $ref: "#/components/schemas/LoadStatus"
        sync_status:
          nullable: true
          $ref: "#/components/schemas/SyncStatus"
    Task:
      description: "迁移任务"
      type: object
      properties:
        name:
          type: string
          example: "task-1"
          description: "迁移任务名，需要全局唯一"
        task_mode:
          type: string
          example: "all"
          description: "迁移模式"
          enum:
            - "full"
            - "incremental"
            - "all"
        shard_mode:
          type: string
          example: "all"
          description: 如果为分库分表合并任务则需要配置该项。默认使用悲观协调模式 "pessimistic"，在深入了解乐观协调模式的原理和使用限制后，也可以设置为乐观协调模式 "optimistic"
          nullable: true
          enum:
            - "pessimistic"
            - "optimistic"
        meta_schema:
          type: string
          example: "dm-meta"
          description: "下游储存 meta 信息的数据库"
        enhance_online_schema_change:
          type: boolean
          example: true
          description: 增强的osc,自适应上游 "gh-ost pt
          nullable: true
        on_duplication:
          type: string
          description: "如何处理有冲突的数据"
          enum:
            - "overwrite"
            - "error"
        target_config:
          $ref: "#/components/schemas/TaskTargetDataBase"
        event_filter:
          type: array
          description: "游数据库实例匹配的表的 binlog event filter 规则集"
          items:
            $ref: "#/components/schemas/TaskEventFilterRule"
        table_migrate_rule:
          type: array
          description: "定义数据源迁移表的过滤规则，可以定义多个规则。如果 DM 版本早于 v2.0.0-beta.2 则使用 black-white-list"
          items:
            $ref: "#/components/schemas/TaskTableMigrateRule"
        source_config:
          type: array
          description: "task 上游数据源的配置列表"
          items:
            $ref: "#/components/schemas/TaskSourceConfig"

    ErrorWithMessage:
      description: "操作错误"
      type: object
      properties:
        error_msg:
          type: string
          description: "失败原因"
        error_code:
          type: integer
          description: "错误码"
